services:
  backend:
    build:
      context: ./
      target: development
      dockerfile: app/infrastructure/Dockerfile
    container_name: backend
    command: sh -c "uvicorn app.main:get_app --factory --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/code

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  dispatcher_worker:
    build:
      context: .
      dockerfile: app/infrastructure/workers/celery.Dockerfile
    container_name: dispatcher_worker
    working_dir: /app
    command: celery -A app.infrastructure.messaging.celery_app:celery_app worker -l debug
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  email_worker:
    build:
      context: .
      dockerfile: app/infrastructure/workers/celery.Dockerfile
    container_name: email_worker
    working_dir: /app
    command: celery -A app.infrastructure.messaging.celery_app:celery_app worker -l info -n email_worker@%h
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  whatsapp_worker:
    build:
      context: .
      dockerfile: app/infrastructure/workers/celery.Dockerfile
    container_name: whatsapp_worker
    working_dir: /app
    command: celery -A app.infrastructure.messaging.celery_app:celery_app worker -l debug -n whatsapp_worker@%h
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  slack_worker:
    build:
      context: .
      dockerfile: app/infrastructure/workers/celery.Dockerfile
    container_name: slack_worker
    working_dir: /app
    command: celery -A app.infrastructure.messaging.celery_app:celery_app worker -l debug -n slack_worker@%h
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: gandalf
      POSTGRES_PASSWORD: ring
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flower:
    build:
      context: .
      dockerfile: app/infrastructure/workers/celery.Dockerfile
    container_name: flower
    command: celery -A app.infrastructure.messaging.celery_app:celery_app flower --port=5555
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
